### ISSUE TITLE
Looking good?

### ISSUE THREAD

**Issue by milankl** [milankl/Float8s.jl#6]
Hey @JeffreySarnoff, following up on our conversation on slack, I adapted the `Float16` code for `Float8`. As you have much more clue about floats than I have, would you mind having a look at it?

**Comment by JeffreySarnoff** [comment]
It looks reasonable.  You definitely need more comprehensive tests. You might consider making some elementary functions table lookups, as that would radically increase the throughput for those functions.

**Comment by JeffreySarnoff** [comment]
You are missing `cbrt`.

**Comment by milankl** [comment]
> It looks reasonable. You definitely need more comprehensive tests. You might consider making some elementary functions table lookups, as that would radically increase the throughput for those functions.

I've added more tests, will leave the performance potential for future releases though. `show` is now also implemented.

**Comment by JeffreySarnoff** [comment]
It is important to support `Base.nextfloat` and `Base.prevfloat`.
One use is autogeneration of function value tables. Another is accuracy determination.

**Comment by milankl** [comment]
`nextfloat`, `prevfloat` are also on master now. Thanks for pointing that out.

**Comment by JeffreySarnoff** [comment]
- `typemin(Float8)` shows as `Inf` (should show as `-Inf`)
- ` nextfloat(typemin(Float8)) is Float8(-15.5)` [now returns `-Inf8`]   
- you should define `promote_rule` for (Float8, FloatN) where N in {16,32,64}
    - `Base.promote_rule(::Type{Float8}, ::Type{Float64}) = Float64` etc
    - otherwise `floatmax(Float8) < floatmax(Float32)` does not work

- bug in `prevfloat`
```
julia> prevfloat(Float8(0))
Float8(-0.015625)

julia> prevfloat(ans)
Float8(-0.0)
```
